# Generated by Django 3.2.13 on 2022-04-21 13:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('status_transaction', models.CharField(choices=[('closed', 'CLOSED'), ('reversed', 'REVERSED'), ('pending', 'PENDING'), ('funding', 'FUNDING'), ('funding-user', 'FUNDING-USER')], default='pending', max_length=25, verbose_name='Status transaction')),
                ('status_approved', models.BooleanField(default=False, verbose_name='Status approved')),
                ('status_cashed', models.BooleanField(default=False, verbose_name='Status cashed')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.company')),
            ],
        ),
    ]
